set ic
set autowrite
set autowriteall
set incsearch
set mouse=a
set number
set relativenumber
set tabstop=4
set softtabstop=4
set shiftwidth=4
set smarttab
set expandtab
set autoindent
set smartindent
set list
set listchars=tab:\|\
set clipboard=unnamedplus
set encoding=UTF-8
set breakindent 
set cursorline 
set linebreak
set signcolumn=yes
set termguicolors
set foldenable
set preserveindent
set splitbelow
set splitright


